<?php
namespace Xenprosys\Ygk\Beanstalk\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator
 */
class BeanstalkServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BeanstalkService
     */
    protected $object;
    protected $mock;
    protected $defaults =
            array('servers' =>
                    array('client' =>
                        array(
                             array('host' => '127.0.0.1', 'port' => 4730)
                    )
                )
            );

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->mock = $this->getMockBuilder('\Pheanstalk_Pheanstalk', array('useTube', 'put'))
            ->disableOriginalConstructor()
            ->getMock();

        $this->mock->expects($this->any())
            ->method('useTube')
            ->will($this->returnValue($this->mock));

        $this->mock->expects($this->any())
            ->method('put')
            ->will($this->returnValue($this->mock));

       $this->object = new BeanstalkService($this->mock, $this->defaults);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Xenprosys\Ygk\Beanstalk\Service\BeanstalkService::__construct
     */
    public function testConfiguration()
    {
        $options = array(
            'servers' => array(
                'client' => array(
                    array('host' => '127.0.0.1', 'port' => 4730),
                    array('host' => '127.0.0.2', 'port' => 4730)
                )
            )
        );

        $this->object = new BeanstalkService($this->mock, $options);
        $this->assertEquals($options['servers'], $this->object->getOption('servers'));

    }

    /**
     * @covers Xenprosys\Ygk\Beanstalk\Service\BeanstalkService::dispatch
     */
    public function testDispatch()
    {
        $key = 'test.job';
        $job = array('id' => $key);
        $this->object->add($key, $job);

        $this->mock->expects($this->once())
                    ->method('put');

        $this->object->dispatch();

    }

    /**
     * @covers Xenprosys\Ygk\Beanstalk\Service\BeanstalkService::dispatch
     */
    public function testDispatchMultipleJobs()
    {
        $key = 'test.job';
        $job = array(array(1), array(2), array(3), array(4), array(5));

        for ($i = 0 ; $i <= 4 ; $i++) {
            $this->object->add($key . $i, $job[$i]);
        }

        $this->mock->
            expects($this->exactly(5))->
            method('put');

        $this->object->dispatch();
    }
}
